### ISSUE TITLE
Backup-SMBSecurity error when not providing a specific descriptor

### ISSUE THREAD

**Issue by nedpyle** [microsoft/SMBSecurity#1]
Repro:

Backup-SMBSecurity

Backup-SMBSecurity: Backup-SMBSecurity - Failed to backup the SrvsvcConfigInfo SecurityDescriptor: The filename, directory name, or volume label syntax is incorrect. : 'C:\Users\nedpyle\AppData\Local\SMBSecurity\Backup-SrvsvcConfigInfo_SrvsvcConnection_SrvsvcFile_SrvsvcServerDiskEnum_SrvsvcSessionInfo_SrvsvcShareAdminConnect_SrvsvcShareAdminInfo_SrvsvcShareChange_SrvsvcShareConnect_SrvsvcShareFileInfo_SrvsvcSharePrintInfo_SrvsvcStatisticsInfo_SrvsvcTransportEnum_SrvsvcDefaultShareInfo-SMBSec-22082022-1112468348.xml'

======

If I provide any descriptor name it works fine. Working repro:

Backup-SMBSecurity -SecurityDescriptor SrvsvcConfigInfo
true

====

I am using PowerShell ver:

winget search Microsoft.PowerShell
Name               Id                           Version Source
---------------------------------------------------------------
PowerShell         Microsoft.PowerShell         7.2.6.0 winget

**Comment by nedpyle** [comment]
It looks like the first parameter is required but then it should be prompting for that

**Comment by JamesKehr** [comment]
This has been fixed in PR #5.
