### ISSUE TITLE
Save-SMBSecurity errors no matter what passed

### ISSUE THREAD

**Issue by nedpyle** [microsoft/SMBSecurity#2]
Repro:

Save-SMBSecurity
InvalidOperation: You cannot call a method on a null-valued expression.

Save-SMBSecurity: Failed to backup: Backup-SMBSecurity - Failed to backup the SrvsvcConfigInfo SecurityDescriptor: The filename, directory name, or volume label syntax is incorrect. : 'C:\Users\nedpyle\AppData\Local\SMBSecurity\Backup-SrvsvcConfigInfo_SrvsvcConnection_SrvsvcFile_SrvsvcServerDiskEnum_SrvsvcSessionInfo_SrvsvcShareAdminConnect_SrvsvcShareAdminInfo_SrvsvcShareChange_SrvsvcShareConnect_SrvsvcShareFileInfo_SrvsvcSharePrintInfo_SrvsvcStatisticsInfo_SrvsvcTransportEnum_SrvsvcDefaultShareInfo-SMBSec-22082022-1119384208.xml'

====

Save-SMBSecurity -SecurityDescriptor SrvsvcShareFileInfo
Save-SMBSecurity: Failed to backup: Backup-SMBSecurity - Failed to backup the SrvsvcConfigInfo SecurityDescriptor: The filename, directory name, or volume label syntax is incorrect. : 'C:\Users\nedpyle\AppData\Local\SMBSecurity\Backup-SrvsvcConfigInfo_SrvsvcConnection_SrvsvcFile_SrvsvcServerDiskEnum_SrvsvcSessionInfo_SrvsvcShareAdminConnect_SrvsvcShareAdminInfo_SrvsvcShareChange_SrvsvcShareConnect_SrvsvcShareFileInfo_SrvsvcSharePrintInfo_SrvsvcStatisticsInfo_SrvsvcTransportEnum_SrvsvcDefaultShareInfo-SMBSec-22082022-1122476715.xml'

====

I've not found a way to make this cmdlet work.

**Comment by JamesKehr** [comment]
Save-SMBSecurity writes/saves an SMB Security Descriptor object to the registry. The cmdlet requires a SMBSec.Descriptor object, which is the output from Get-SMBSecurity.

The basic workflow:

- $SD = Get-SMBSecurity <SD name>
- Modify SD
- Save-SMBSecurity $SD

I'll add some validation and error output to handle incorrect inputs.

**Comment by JamesKehr** [comment]
The Save cmdlet commits changes to the SMBSecurityDescriptor object to the registry. The backup is automatic and is performed by Backup-SMBSecurity.

 This will be addressed by documentation in the [SMBSecurity Wiki](https://github.com/microsoft/SMBSecurity/wiki). Specifically in the [Save-SMBSecurity](https://github.com/microsoft/SMBSecurity/wiki/Save%E2%80%90SMBSecurity) command reference and the How-to guides.
