### ISSUE TITLE
Save-SMBSecurity specify paths?

### ISSUE THREAD

**Issue by nedpyle** [microsoft/SMBSecurity#3]
The Save-SMBSecurity cmdlet doesn't have a path output parameter like the Backup-SMBSecurity cmdlet. It always tries to write to a very deep %appdata% xml file path in my attempts.

**Comment by JamesKehr** [comment]
Fixed in PR #6. 

Added the following parameters to Save-SMBSecurity:

- BackupPath - Backs up files to this path rather than the automatic backup path.
- BackupWithRegFile - Also creates a complete backup using a registry export of the SMB SecurityDescriptors.
